@startuml

class Display {
    impl
    {method} open
    {method} print
    {method} close
    {method} display
}

class DisplayImpl {
    {method} rawOpen
    {method} rawPrint
    {method} rawClose
}

class CountDisplay {
    {method} multiDisplay
}

class RandomCountDisplay {
    {method} randomDisplay
}

class StringDisplayImpl {
    {method} rawOpen
    {method} rawPrint
    {method} rawClose
}

Display o--> DisplayImpl

Display <|-- CountDisplay
CountDisplay <|-- RandomCountDisplay

DisplayImpl <|-- StringDisplayImpl

@enduml